# FFmpeg test videos
# A collection of test videos generated by FFmpeg
# Github: https://www.github.com/0x4248/FFmpeg_test_videos
# Licence: GNU General Public License v3.0
# By: 0x4248
#
# Makefile
# Main makefile for the project

include tools/variables.sh

all: clean run

clean:
	rm -rf $(OUTPUT)
	mkdir -p $(OUTPUT)

run:
	bash src/generate.sh